version: '3.9'
services:
  database:
    image: postgres:16-alpine
    env_file:
      - .test.env
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $DB_USER -d $DB_NAME"
      interval: 1s
      retries: 5
  test-runner:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .test.env