version: '3'
services:
  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $DB_USER -d $DB_NAME"
      interval: 1s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
