version: '3.9'
services:
  database:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $DB_USER -d $DB_NAME"
      interval: 1s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/
    ports:
      - "8080:80"
    command: "--reload --host 0.0.0.0 --port 80"
    depends_on:
      database:
        condition: service_healthy
