version: '3'
services:
  database:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 0.3s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env