version: '3'
services:
  database:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - database
    env_file:
      - .env