FROM python:3.12.1-slim-bullseye

WORKDIR /app

COPY poetry.lock pyproject.toml ./

ENV POETRY_VIRTUALENVS_CREATE=false 

RUN pip install poetry 

RUN poetry install

COPY src ./src/

COPY tests ./tests/

